MilitaryScheduler/MilitaryScheduler/ViewModels/RequestViewModel.cs
namespace MilitaryScheduler.ViewModels
{
    public class RequestViewModel
    {
        public string TargetUser { get; set; }
        public string TargetedUser { get; set; }
        public string RequestId { get; set; }
        public string Date { get; set; }
    }
}

MilitaryScheduler/MilitaryScheduler/ViewModels/RequestsViewModel.cs
using System.Collections.Generic;

namespace MilitaryScheduler.ViewModels
{
    public class RequestsViewModel
    {
        public IEnumerable<RequestViewModel> RequestsList {get; set;}
    }
}

MilitaryScheduler/MilitaryScheduler/Controllers/RequestsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MilitaryScheduler.Data;
using MilitaryScheduler.Models;
using MilitaryScheduler.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace MilitaryScheduler.Controllers
{
    public class RequestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public RequestsController(ApplicationDbContext context,
                                  UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            if (_userManager.FindByIdAsync(User.FindFirstValue(ClaimTypes.NameIdentifier)).Result.IsSystemAdmin)
            {
                return View(PrepareModel());
            }
            else
            {
                return View("MyRequests", PrepareModel());
            }
        }

        public IActionResult MyRequests()
        {
            return View(PrepareModel());
        }



        public IActionResult ApproveEventRequest(string requestId)
        {
            if (int.TryParse(requestId, out int rid))
            {
                var request = _context.Requests.First(r => r.Id == rid);
                if (int.TryParse(request.EventId, out int evId))
                {
                    var calendarEvent = _context.Events.FirstOrDefault(e => e.Id == evId);
                    if (calendarEvent != null)
                    {
                        calendarEvent.UserId = request.TargetUserId;
                        var targetUser = _context.Users.First(u => u.Id == request.TargetUserId);
                        calendarEvent.Text = targetUser.UserName;
                        _context.Requests.Remove(request);
                        _context.SaveChanges();
                    }
                }
            }

            return Index();
        }

        public IActionResult DeleteEventRequest(string requestId)
        {
            if (int.TryParse(requestId, out int rid))
            {
                var request = _context.Requests.First(r => r.Id == rid);
                if (int.TryParse(request.EventId, out int evId))
                {
                    _context.Requests.Remove(request);
                    _context.SaveChanges();
                }
            }

            return Index();
        }

        private RequestsViewModel PrepareModel()
        {
            var requestsViewModel = new RequestsViewModel();
            CreateRequestsList(requestsViewModel);
            return requestsViewModel;
        }

        private void CreateRequestsList(RequestsViewModel requestsViewModel)
        {
            List<RequestModel> requests = new List<RequestModel>();
            var currentUser = _userManager.FindByIdAsync(User.FindFirstValue(ClaimTypes.NameIdentifier)).Result;
            if (currentUser != null)
            {
                if (currentUser.IsSystemAdmin)
                {
                    requests = _context.Requests.ToList();
                }
                else
                {
                    requests = _context.Requests.Where(r => r.TargetedUserId == currentUser.Id || r.TargetUserId == currentUser.Id).ToList();
                }
            }
            
            var requestsList = new List<RequestViewModel>();
            if (requests.Count > 0)
            {
                foreach (var request in requests)
                {
                    var targetUserName = _userManager.FindByIdAsync(request.TargetUserId).Result.UserName;
                    var targetedUserName = _userManager.FindByIdAsync(request.TargetedUserId).Result.UserName;

                    requestsList.Add(new RequestViewModel()
                    {
                        TargetedUser = targetedUserName,
                        TargetUser = targetUserName,
                        RequestId = request.Id.ToString(),
                        Date = request.Date
                    });

                    requestsViewModel.RequestsList = requestsList;
                }
            }
            else
            {
                requestsViewModel.RequestsList = requestsList;
            }
        }
    }
}

MilitaryScheduler/MilitaryScheduler/Views/Requests/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using MilitaryScheduler.ViewModels

@model RequestsViewModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<script src="~/js/daypilot/daypilot-all.min.js" asp-append-version="true"></script>
<link href="icons/style.css" rel="stylesheet" type="text/css">


@if (SignInManager.IsSignedIn(User))
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">From</th>
                <th scope="col">To</th>
                <th scope="col">Date</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var request in Model.RequestsList)
            {
                <tr>
                    <th scope="row">@request.RequestId</th>
                    <td>@request.TargetUser</td>
                    <td>@request.TargetedUser</td>
                    <td>@request.Date</td>
                    <td><a asp-area="" asp-controller="Requests" asp-action="ApproveEventRequest" asp-route-requestId="@request.RequestId">Approve</a></td>
                    <td><a asp-area="" asp-controller="Requests" asp-action="DeleteEventRequest" asp-route-requestId="@request.RequestId">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <img src="~/images/stemaAtm.png" width="150px" style="padding-top:30px; display:flex; position:absolute" alt="Image" />
    <div style="width:100%; margin-left ">
        <img src="~/images/background.jpg" style="margin-left:-500px; opacity:50%;" alt="Image" />
    </div>

    <p class="mega">
        ATM Scheduler
    </p>
    <p class="mini">Please login in order to access the time scheduler.</p>
}

MilitaryScheduler/MilitaryScheduler/Views/Requests/MyRequests.cshtml
@using Microsoft.AspNetCore.Identity
@using MilitaryScheduler.ViewModels

@model RequestsViewModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    var targetedRequestsList = new List<RequestViewModel>();
    var targetRequestsList = new List<RequestViewModel>();
    if (Model.RequestsList != null && Model.RequestsList.Any())
    {
        targetedRequestsList = Model.RequestsList.Where(r => r.TargetedUser == User.Identity.Name).ToList();
        targetRequestsList = Model.RequestsList.Where(r => r.TargetUser == User.Identity.Name).ToList();
    }
}


<script src="~/js/daypilot/daypilot-all.min.js" asp-append-version="true"></script>
<link href="icons/style.css" rel="stylesheet" type="text/css">


@if (SignInManager.IsSignedIn(User))
{
    <h2>Requests to approve</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">From</th>
                <th scope="col">Date</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var request in targetedRequestsList)
            {
                <tr>
                    <td>@request.TargetUser</td>
                    <td>@request.Date</td>
                    <td><a asp-area="" asp-controller="Requests" asp-action="ApproveEventRequest" asp-route-requestId="@request.RequestId">Approve</a></td>
                    <td><a asp-area="" asp-controller="Requests" asp-action="DeleteEventRequest" asp-route-requestId="@request.RequestId">Decline</a></td>
                </tr>
            }
        </tbody>
    </table>

    <hr />

    <h2>Your Requests</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">To</th>
                <th scope="col">Date</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var request in targetRequestsList)
            {
                <tr>
                    <td>@request.TargetedUser</td>
                    <td>@request.Date</td>
                    <td><a asp-area="" asp-controller="Requests" asp-action="DeleteEventRequest" asp-route-requestId="@request.RequestId">Decline</a></td>
                </tr>
            }
        </tbody>
    </table>

}
else
{
    <p class="mega">
        Military Scheduler
    </p>
    <p class="mini">Please login in order to access the time scheduler.</p>
}